# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Add shield to app icon"
  lane :add_shield do
    add_badge(
      shield: "#{ENV['DEMO_VERSION']}-#{ENV['BUILD_VARIANT']}-blue",
      shield_gravity: 'South',
      no_badge: true
    )
  end
end
