name: feature-bugfix
on: 
  workflow_dispatch:
  pull_request:
    branches:    
      - develop
      
jobs:
  #swiftlint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: SwiftLint (Only files changed in the PR)
  #      uses: norio-nomura/action-swiftlint@3.2.1
  #      env:
  #        DIFF_BASE: ${{ github.base_ref }}

  gpt-code-review:
    name: 'GPT Code Review'
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: gpt-review
        uses: microsoft/gpt-review@v0.9.4
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_ORG_KEY: 'org-ReuxU2hMoVFAGXSBEtdMOQ2y'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
  test-unit:
    name: Unit Test
  #  needs: swiftlint
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: xcodebuild Test
        uses: sersoft-gmbh/xcodebuild-action@v2.1
        with:
          project: GithubActionDemo.xcodeproj
          scheme: GithubActionDemo
          derived-data-path: .derived_data
          destination: platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro
          output-formatter: xcbeautify
          enable-code-coverage: true
          action: clean test
      - shell: bash
        name: Convert test results
        if: always()
        run: |
          mkdir test_results
          xcresultparser -o junit --coverage .derived_data/Logs/Test/*.xcresult > test_results/report.junit
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit Test Report            
          path: test_results/report.junit
          reporter: java-junit 

  #build-archive:
  #  name: Archive
  #  needs: test-unit
  #  runs-on: self-hosted
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: xcodebuild Archive
  #      uses: sersoft-gmbh/xcodebuild-action@v2.1
  #      with:
  #        project: GithubActionDemo.xcodeproj
  #        scheme: GithubActionDemo
  #        sdk: iphoneos
  #        output-formatter: xcbeautify
  #        action: clean archive