name: feature-bugfix
on: 
  workflow_dispatch:
  pull_request:
    branches:    
      - develop
      
jobs:
  #swiftlint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: SwiftLint (Only files changed in the PR)
  #      uses: norio-nomura/action-swiftlint@3.2.1
  #      env:
  #        DIFF_BASE: ${{ github.base_ref }}
  
  test-unit:
    name: Unit Test
  #  needs: swiftlint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: xcodebuild Test
        uses: sersoft-gmbh/xcodebuild-action@v2.1
        with:
          project: GithubActionDemo.xcodeproj
          scheme: GithubActionDemo
          derived-data-path: .derived_data
          destination: platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro
          output-formatter: xcbeautify
          enable-code-coverage: true
          action: clean test
      - shell: bash
        name: Convert test results
        if: always()
        run: |
          mkdir test_results
          xsltproc -o test_results/report.junit \
          .github/plist_to_junit.xsl \
          .derived_data/Logs/Test/*_TestSummaries.plist
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            test_results/report.junit

  #build-archive:
  #  name: Archive
  #  needs: test-unit
  #  runs-on: self-hosted
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: xcodebuild Archive
  #      uses: sersoft-gmbh/xcodebuild-action@v2.1
  #      with:
  #        project: GithubActionDemo.xcodeproj
  #        scheme: GithubActionDemo
  #        sdk: iphoneos
  #        output-formatter: xcbeautify
  #        action: clean archive