name: "Feature/Bugfix"
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop

env:
  BUILD_VARIANT: Branch
      
jobs:
  swiftlint:
    name: Swiftlint
    uses: ./.github/workflows/reusable/swiftlint.yml
  
  test-unit:
    name: Unit Test
    uses: ./.github/workflows/reusable/test-unit.yml

  build-archive:
    name: Archive (${{ github.run_id }})
    needs: test-unit
    uses: ./.github/workflows/reusable/build-archive.yml
    with:
      version: '1.0.0'
      bundle-id: de.adesso-mobile.research.ghademo.branch
      backend: dev
      provisioning-profile: GithubActionDemoWildcardAdHoc
      shield-color: blue
      build-variant: Branch
      export-options: ExportOptionsWildcardAdHoc
        
  deploy-to-appcenter:
    name: Deploy To AppCenter
    needs: build-archive
    uses: ./.github/workflows/reusable/deploy-to-appcenter.yml
    with:
      build-variant: Branch
      distribution-groups: Collaborators
      appcenter-app-name: nholloh-ams/Github-Action-Demo-Feature-Bugfix