name: feature-bugfix
on: 
  workflow_dispatch:
  pull_request:
    branches:    
      - develop
      
jobs:
  #swiftlint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: SwiftLint (Only files changed in the PR)
  #      uses: norio-nomura/action-swiftlint@3.2.1
  #      env:
  #        DIFF_BASE: ${{ github.base_ref }}

  gpt-code-review:
    name: 'GPT Code Review'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_HEAD_REF }}" > "diff.txt"
          # shellcheck disable=SC2086
          echo "diff=$(cat "diff.txt")" >> $GITHUB_ENV
      - uses: yu-iskw/gpt-code-review-action@v0.3.0
        name: "Code Review by GPT"
        id: review
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ github.token }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gpt-3.5-turbo"
          temperature: "0.1"
          max_tokens: "512"
          top_p: "1"
          frequency_penalty: "0.0"
          presence_penalty: "0.0"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: |-
            You are very familiar with python too.
          log_level: "DEBUG"
  
  test-unit:
    name: Unit Test
  #  needs: swiftlint
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: xcodebuild Test
        uses: sersoft-gmbh/xcodebuild-action@v2.1
        with:
          project: GithubActionDemo.xcodeproj
          scheme: GithubActionDemo
          derived-data-path: .derived_data
          destination: platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro
          output-formatter: xcbeautify
          enable-code-coverage: true
          action: clean test
      - shell: bash
        name: Convert test results
        if: always()
        run: |
          mkdir test_results
          xcresultparser -o junit --coverage .derived_data/Logs/Test/*.xcresult > test_results/report.junit
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit Test Report            
          path: test_results/report.junit
          reporter: java-junit 

  #build-archive:
  #  name: Archive
  #  needs: test-unit
  #  runs-on: self-hosted
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: xcodebuild Archive
  #      uses: sersoft-gmbh/xcodebuild-action@v2.1
  #      with:
  #        project: GithubActionDemo.xcodeproj
  #        scheme: GithubActionDemo
  #        sdk: iphoneos
  #        output-formatter: xcbeautify
  #        action: clean archive