name: "Feature/Bugfix"
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop

env:
  BUILD_VARIANT: Branch
      
jobs:
  swiftlint:
    name: Swiftlint
    uses: ./.github/workflows/swiftlint.yml
  
  test-unit:
    name: Unit Test
    permissions: write-all
    uses: ./.github/workflows/test-unit.yml

  compute-version:
    name: Compute Version
    permissions: write-all
    uses: ./.github/workflows/compute-version.yml
    with:
      read-only: true

  build-archive:
    name: Archive ${{ needs.compute-version.outputs.computed-version }} (${{ github.run_id }})
    needs: [test-unit, compute-version]
    uses: ./.github/workflows/build-archive.yml
    secrets: inherit
    with:
      version: ${{ needs.compute-version.outputs.computed-version }}
      bundle-id: de.adesso-mobile.research.ghademo.branch
      backend: dev
      provisioning-profile: GithubActionDemoWildcardAdHoc
      shield-color: blue
      build-variant: Branch
      export-options: ExportOptionsWildcardAdHoc
        
  deploy-to-appcenter:
    name: Deploy To AppCenter
    needs: build-archive
    uses: ./.github/workflows/deploy-to-appcenter.yml
    secrets: inherit
    with:
      build-variant: Branch
      distribution-groups: Collaborators
      appcenter-app-name: nholloh-ams/Github-Action-Demo-Feature-Bugfix